export interface SgCoefficients {
  readonly window: number;
  readonly poly: number;
  readonly interior: readonly number[];
  readonly leadingEdge: readonly (readonly number[])[];
  readonly trailingEdge: readonly (readonly number[])[];
  readonly version: string;
}

/**
 * Frozen seg-v2 Savitzky-Golay constants.
 *
 * Generated by:
 * research/src/modules/kinematics/notebooks/t1/generate_promoted_kinematics_golden.py
 * Golden: research/fixtures/golden/sg-coeffs-seg-v2.json
 * Date: 2026-08-17
 * Source params: research/src/modules/segments/algorithms/submovement.py SEG_V2_PARAMS
 */
export const SG_SEG_V2: SgCoefficients = {
  version: 'sg-seg-v2',
  window: 11,
  poly: 3,
  interior: [
    -0.08391608391608417,
    0.020979020979021018,
    0.10256410256410284,
    0.16083916083916128,
    0.19580419580419633,
    0.20745920745920804,
    0.19580419580419633,
    0.16083916083916128,
    0.10256410256410284,
    0.020979020979021018,
    -0.08391608391608417,
  ],
  leadingEdge: [
    [
      0.7902097902097882,
      0.3356643356643363,
      0.05594405594405694,
      -0.08391608391608348,
      -0.11888111888111841,
      -0.08391608391608364,
      -0.013986013986014203,
      0.05594405594405507,
      0.09090909090909068,
      0.05594405594405527,
      -0.08391608391608321,
    ],
    [
      0.335664335664334,
      0.286713286713287,
      0.2237762237762248,
      0.1538461538461549,
      0.08391608391608435,
      0.020979020979021268,
      -0.027972027972028413,
      -0.055944055944057026,
      -0.05594405594405656,
      -0.02097902097902099,
      0.055944055944056575,
    ],
    [
      0.05594405594405438,
      0.22377622377622386,
      0.28671328671328783,
      0.2703962703962719,
      0.2004662004662009,
      0.10256410256410288,
      0.002331002331001728,
      -0.07459207459207584,
      -0.10256410256410338,
      -0.055944055944055715,
      0.09090909090909166,
    ],
    [
      -0.08391608391608552,
      0.1538461538461539,
      0.2703962703962717,
      0.29254079254079446,
      0.24708624708624755,
      0.16083916083916122,
      0.06060606060605986,
      -0.026806526806528265,
      -0.07459207459207541,
      -0.05594405594405574,
      0.05594405594405699,
    ],
    [
      -0.11888111888112074,
      0.08391608391608407,
      0.20046620046620178,
      0.24708624708624943,
      0.24009324009324062,
      0.19580419580419617,
      0.13053613053612972,
      0.06060606060605913,
      0.0023310023310014333,
      -0.02797202797202808,
      -0.013986013986012652,
    ],
  ],
  trailingEdge: [
    [
      -0.013986013986016399,
      -0.027972027972027524,
      0.0023310023310040354,
      0.06060606060606359,
      0.13053613053613133,
      0.19580419580419617,
      0.24009324009323904,
      0.2470862470862453,
      0.20046620046619978,
      0.08391608391608305,
      -0.1188811188811165,
    ],
    [
      0.055944055944053606,
      -0.05594405594405538,
      -0.07459207459207268,
      -0.026806526806523248,
      0.06060606060606122,
      0.16083916083916128,
      0.24708624708624596,
      0.29254079254079085,
      0.2703962703962695,
      0.15384615384615277,
      -0.08391608391608127,
    ],
    [
      0.09090909090908861,
      -0.05594405594405527,
      -0.10256410256410087,
      -0.07459207459207047,
      0.0023310023310031402,
      0.10256410256410296,
      0.20046620046619915,
      0.27039627039626846,
      0.28671328671328583,
      0.22377622377622253,
      0.05594405594405924,
    ],
    [
      0.05594405594405383,
      -0.02097902097902027,
      -0.05594405594405407,
      -0.05594405594405129,
      -0.027972027972026914,
      0.020979020979021448,
      0.08391608391608227,
      0.1538461538461515,
      0.22377622377622297,
      0.2867132867132857,
      0.3356643356643396,
    ],
    [
      -0.08391608391608574,
      0.05594405594405649,
      0.0909090909090921,
      0.055944055944062196,
      -0.01398601398601318,
      -0.08391608391608364,
      -0.11888111888112061,
      -0.08391608391608588,
      0.05594405594405412,
      0.33566433566433523,
      0.7902097902097941,
    ],
  ],
};

export function sgSmooth(values: readonly number[], coeffs: SgCoefficients = SG_SEG_V2): number[] {
  validateCoefficients(coeffs);
  if (values.length < coeffs.window) {
    throw new Error(`x has ${values.length} samples, fewer than window=${coeffs.window}`);
  }
  for (let i = 0; i < values.length; i++) {
    if (!Number.isFinite(values[i])) throw new Error('x must contain only finite values');
  }

  const output = new Array<number>(values.length);
  const half = (coeffs.window - 1) / 2;
  for (let i = 0; i < half; i++) {
    output[i] = dot(coeffs.leadingEdge[i], values, 0);
  }
  for (let i = half; i < values.length - half; i++) {
    output[i] = dot(coeffs.interior, values, i - half);
  }
  const trailingStart = values.length - coeffs.window;
  for (let i = 0; i < half; i++) {
    output[values.length - half + i] = dot(coeffs.trailingEdge[i], values, trailingStart);
  }
  return output;
}

function validateCoefficients(coeffs: SgCoefficients): void {
  if (!Number.isInteger(coeffs.window) || coeffs.window <= 0 || coeffs.window % 2 === 0) {
    throw new Error('window must be a positive odd integer');
  }
  if (!Number.isInteger(coeffs.poly) || coeffs.poly < 0) {
    throw new Error('poly must be a non-negative integer');
  }
  if (coeffs.poly >= coeffs.window) throw new Error('poly must be less than window');
  if (!coeffs.version.trim()) throw new Error('version must be a non-empty string');
  const half = (coeffs.window - 1) / 2;
  validateRow(coeffs.interior, coeffs.window, 'interior');
  validateMatrix(coeffs.leadingEdge, half, coeffs.window, 'leadingEdge');
  validateMatrix(coeffs.trailingEdge, half, coeffs.window, 'trailingEdge');
}

function validateMatrix(
  matrix: readonly (readonly number[])[],
  expectedRows: number,
  expectedColumns: number,
  name: string,
): void {
  if (matrix.length !== expectedRows) throw new Error(`${name} must contain ${expectedRows} rows`);
  for (let i = 0; i < matrix.length; i++) validateRow(matrix[i], expectedColumns, `${name}[${i}]`);
}

function validateRow(row: readonly number[], expectedLength: number, name: string): void {
  if (row.length !== expectedLength) throw new Error(`${name} must contain ${expectedLength} coefficients`);
  for (const value of row) {
    if (!Number.isFinite(value)) throw new Error(`${name} must contain only finite coefficients`);
  }
}

function dot(coefficients: readonly number[], values: readonly number[], start: number): number {
  let total = 0;
  for (let i = 0; i < coefficients.length; i++) {
    total += coefficients[i] * values[start + i];
  }
  return total;
}
