"""WP-31 / T1 -- ONE-OFF generator for `research/fixtures/golden/sparc-128hz-domain.json`.

This is the only script in the repo that is *allowed* to reach into `performance_analysis`, and it
is never run by pytest or by any report. It exists so the 128 Hz-domain golden's expected values come
from **PA's implementation**, not from ours -- a golden generated by the code it is supposed to
verify proves nothing (README §2, C-D1).

How the boundary is kept:

- PA is executed in a **subprocess** with `PYTHONPATH` pointed at PA's own `research/src`. Our
  `modules` package is a regular package, so PA's same-named `modules` package could never be
  imported side by side anyway -- the subprocess makes that separation explicit rather than fragile.
- Nothing imports this module at runtime; the committed JSON is the only artefact that crosses.
- PA's repo path and resolved commit hash are written into the golden's `provenance` block and are
  asserted by `test_sparc.py`.

Usage (requires performance_analysis checked out locally)::

    uv run python src/modules/metrics/notebooks/t1/generate_sparc_domain_golden.py
    PA_REPO=/path/to/performance_analysis uv run python .../generate_sparc_domain_golden.py

Cases written:

- >= 2 real MR intervals in each zero-padding bucket (`n_fft` 32 and 64), taken in deterministic
  roster/peek order from the three `tick-integral` fixtures -- these fix this project's own sampling
  domain, which the 1 kHz PA parity case cannot.
- 4 synthetic edge cases (`len=15` below `MIN_SAMPLES`, `len=16` exactly at it, a constant series,
  and a series containing NaN) -- the degenerate branches, whose PA-defined return values
  (`0.0`, never NaN, except for NaN input) are the easiest thing to "improve" by accident.
"""

from __future__ import annotations

from dataclasses import replace
from datetime import date
import json
import os
from pathlib import Path
import subprocess
import sys

import numpy as np


RESEARCH_ROOT = Path(__file__).resolve().parents[5]
SOURCE_ROOT = RESEARCH_ROOT / "src"
if str(SOURCE_ROOT) not in sys.path:
    sys.path.insert(0, str(SOURCE_ROOT))

from modules.ingest.algorithms import load_export  # noqa: E402
from modules.kinematics.algorithms.angular import omega_deg_s  # noqa: E402
from modules.metrics.algorithms.peek import build_peek_windows  # noqa: E402
from modules.metrics.algorithms.sparc import MIN_SAMPLES, padded_length  # noqa: E402
from modules.segments.algorithms import SEG_V2_PARAMS, segment_submovements  # noqa: E402


EXPORT_DIR = RESEARCH_ROOT / "fixtures" / "exports"
GOLDEN_PATH = RESEARCH_ROOT / "fixtures" / "golden" / "sparc-128hz-domain.json"

#: T0/D-30.2 roster (WP-31 README §0.1) -- `tick-integral` exports only.
REAL_FIXTURES = (
    EXPORT_DIR / "counterstrafe_ad_v1-2026-08-07T09_18_05.631Z.json",
    EXPORT_DIR / "counterstrafe_ad_v1-2026-08-07T09_24_18.148Z.json",
    EXPORT_DIR / "counterstrafe_ad_v1-2026-08-07T09_37_24.351Z.json",
)

FS_HZ = 128.0
#: How many real MR intervals to capture per padding bucket (T1 DoD 3 asks for >= 2).
PER_BUCKET = 2

DEFAULT_PA_REPO = RESEARCH_ROOT.parents[1] / "performance_analysis"

_PA_RUNNER = """
import json, sys
import numpy as np
from modules.analysis.algorithms.metrics_sparc import compute_sparc

payload = json.load(sys.stdin)
out = []
for case in payload:
    value = float(compute_sparc(np.asarray(case["velocity_series"], dtype=float), case["fs"]))
    out.append(None if value != value else value)
json.dump(out, sys.stdout)
"""


def real_mr_cases() -> list[dict]:
    """Deterministically pick the first `PER_BUCKET` MR intervals found in each padding bucket."""

    picked: dict[int, list[dict]] = {32: [], 64: []}
    for source in REAL_FIXTURES:
        export = load_export(source)
        ticks = export.ticks.sort_values("t", kind="stable").reset_index(drop=True)
        for peek in build_peek_windows(export):
            window_ticks = ticks.iloc[peek.tick_slice].reset_index(drop=True)
            omega = omega_deg_s(window_ticks, strict=True).values
            raw = segment_submovements(omega[1:], SEG_V2_PARAMS) if len(omega) > 1 else []
            # Same +1 index mapping back into the window frame as generate_phase_report.py.
            segments = [replace(segment, start_idx=segment.start_idx + 1, end_idx=segment.end_idx + 1) for segment in raw]
            primary = next((segment for segment in segments if segment.kind == "primary_flick"), None)
            if primary is None:
                continue
            n_ticks = primary.end_idx - primary.start_idx + 1
            if n_ticks < MIN_SAMPLES:
                continue
            bucket = padded_length(n_ticks)
            if bucket not in picked or len(picked[bucket]) >= PER_BUCKET:
                continue
            series = omega[primary.start_idx : primary.end_idx + 1]
            picked[bucket].append(
                {
                    "name": f"real_{source.stem[-13:-1].replace('_', '')}_peek{peek.index:02d}_n{n_ticks}",
                    "kind": "real_mr_segment",
                    "source_fixture": source.name,
                    "peek_index": peek.index,
                    "side": peek.side,
                    "start_idx": int(primary.start_idx),
                    "end_idx": int(primary.end_idx),
                    "n_ticks": int(n_ticks),
                    "n_fft": int(bucket),
                    "fs": FS_HZ,
                    "velocity_series": [float(value) for value in series],
                }
            )
    return [case for bucket in sorted(picked) for case in picked[bucket]]


def synthetic_edge_cases() -> list[dict]:
    ramp = np.linspace(10.0, 180.0, MIN_SAMPLES)
    with_nan = ramp.copy()
    with_nan[MIN_SAMPLES // 2] = np.nan
    specs = (
        ("edge_len15_below_min_samples", np.linspace(10.0, 180.0, MIN_SAMPLES - 1)),
        ("edge_len16_exactly_min_samples", ramp),
        ("edge_constant_series", np.zeros(32)),
        ("edge_contains_nan", with_nan),
    )
    return [
        {
            "name": name,
            "kind": "synthetic_edge",
            "n_ticks": int(series.size),
            "n_fft": int(padded_length(series.size)) if series.size >= MIN_SAMPLES else None,
            "fs": FS_HZ,
            "velocity_series": [None if np.isnan(value) else float(value) for value in series],
        }
        for name, series in specs
    ]


def run_pa(cases: list[dict], pa_repo: Path) -> list[float | None]:
    """Evaluate every case with performance_analysis's own `compute_sparc`, out of process."""

    pa_source = pa_repo / "research" / "src"
    if not (pa_source / "modules" / "analysis" / "algorithms" / "metrics_sparc.py").exists():
        raise SystemExit(f"performance_analysis not found under {pa_repo} (set PA_REPO)")

    env = os.environ.copy()
    env["PYTHONPATH"] = str(pa_source)
    env["PYTHONDONTWRITEBYTECODE"] = "1"
    payload = [
        {
            "fs": case["fs"],
            "velocity_series": [float("nan") if value is None else value for value in case["velocity_series"]],
        }
        for case in cases
    ]
    completed = subprocess.run(
        [sys.executable, "-c", _PA_RUNNER],
        input=json.dumps(payload),
        env=env,
        cwd=pa_source,
        capture_output=True,
        text=True,
        check=True,
    )
    return json.loads(completed.stdout)


def pa_commit(pa_repo: Path) -> str:
    return subprocess.run(
        ["git", "-C", str(pa_repo), "rev-parse", "HEAD"],
        capture_output=True,
        text=True,
        check=True,
    ).stdout.strip()


def main() -> None:
    pa_repo = Path(os.environ.get("PA_REPO", DEFAULT_PA_REPO)).resolve()
    cases = real_mr_cases() + synthetic_edge_cases()
    expected = run_pa(cases, pa_repo)

    for case, value in zip(cases, expected, strict=True):
        case["expected_sparc"] = value  # null == NaN; JSON has no NaN literal.

    payload = {
        "provenance": {
            "source_repo": "performance_analysis",
            "source_path": "research/src/modules/analysis/algorithms/metrics_sparc.py",
            "source_commit": pa_commit(pa_repo),
            "generated_on": date.today().isoformat(),
            "generator": "research/src/modules/metrics/notebooks/t1/generate_sparc_domain_golden.py",
            "note": (
                "Expected values produced by performance_analysis's own compute_sparc, run in a "
                "subprocess. This repo never imports performance_analysis at runtime or under "
                "pytest (C-D1); only this committed JSON crosses the boundary."
            ),
        },
        "fs_hz": FS_HZ,
        "cases": cases,
    }
    GOLDEN_PATH.parent.mkdir(parents=True, exist_ok=True)
    GOLDEN_PATH.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {GOLDEN_PATH} ({len(cases)} cases, PA commit {payload['provenance']['source_commit'][:12]})")


if __name__ == "__main__":
    main()
